N DC INTEGER(5)
ONE DC INTEGER(1)
TEN DC INTEGER(10)
WYNIK DC INTEGER(1)
#Ustawaiamy zakres petli
 L 1,N
 L 2,WYNIK
#Wejscie do petli
IN_LOOP MR 2,1
 S 1,ONE
IF_START C 2,TEN
 JZ SUB
 JP SUB
 JN LOOP_END
SUB S 2,TEN
 J IF_START
LOOP_END C 1,ONE
 JP IN_LOOP
 ST 2,WYNIK