# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'complex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cmath

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(399, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 381, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout_2.addWidget(self.lineEdit2, 1, 1, 1, 1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout_2.addWidget(self.lineEdit1, 0, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)
        self.answer = QtWidgets.QLabel(self.gridLayoutWidget)
        self.answer.setText("")
        self.answer.setObjectName("answer")
        self.gridLayout_2.addWidget(self.answer, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        QtWidgets.QListWidgetItem("+", self.listWidget)
        QtWidgets.QListWidgetItem("-", self.listWidget)
        QtWidgets.QListWidgetItem("/", self.listWidget)
        QtWidgets.QListWidgetItem("*", self.listWidget)
        QtWidgets.QListWidgetItem("abs (only for firstNumber)", self.listWidget)
        QtWidgets.QListWidgetItem("trigonometric form (only for firstNumber)", self.listWidget)
        self.addFunction()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "SecondNumber"))
        self.label_2.setText(_translate("MainWindow", "FirstNumber"))
        self.label_4.setText(_translate("MainWindow", "Action"))
        self.label.setText(_translate("MainWindow", "Answer: "))
        self.pushButton.setText(_translate("MainWindow", "="))
        self.label_5.setText(_translate("MainWindow", "Complex calc :) (use j)"))

    def addFunction(self):
        self.pushButton.clicked.connect(self.results)

    def results(self):
        firstStr = self.lineEdit1.text().replace(" ", "")
        if firstStr == "":
            firstStr = '0'
        first = complex(firstStr)

        secondStr = self.lineEdit2.text().replace(" ", "")
        if secondStr == "":
            secondStr = '0'
        second = complex(secondStr)

        action = self.listWidget.currentItem().text()

        if action == "+":
            ans = first + second
        elif action == "-":
            ans = first - second
        elif action == "*":
            ans = first * second
        elif action == "/":
            ans = first / second
            r = round(ans.real, 5)
            i = round(ans.imag, 5)
            ans = complex(r, i)
        elif action[:3] == "abs":
            ans = abs(first)
        elif action[:5] == "trigo":
            radius, angle = cmath.polar(first)
            angle = round(angle, 4)
            print(angle)
            ans = f"{round(radius, 4)}*(cos({angle}) + j*sin({angle}))"
        self.answer.setText(str(ans))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
